# Source: eschart/templates/deployment.yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ha
  labels:
    app: elasticsearchnode
spec:
  metadata:
    labels:
      app: elasticsearchnode
  secureSettings:
  - secretName: "snapshot-secret"
  version: 7.5.2
  nodeSets:
  - name: esnode
    count: 3
    config:
      node.master: true
      node.data: true
      node.ingest: true
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        - name: install-plugin
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch repository-azure
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  elasticsearch.k8s.elastic.co/cluster-name: ha
              topologyKey: kubernetes.io/hostname
    volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
            annotations:
              nfs.io/storage-path: "/mnt/myshareddir"
          spec:
            storageClassName: nfs-client
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi